allowEmptyPassword: "yes"
externalDatabase:
  database: bitnami_moodle
  host: null
  password: null
  port: 3306
  user: bn_moodle
image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: bitnami/moodle
  tag: 3.8.2-debian-10-r0
ingress:
  enabled: false
  hosts:
  - annotations: null
    certManager: false
    name: moodle.local
    tls: false
    tlsSecret: moodle.local-tls
  secrets: null
livenessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 600
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
mariadb:
  db:
    name: bitnami_moodle
    user: bn_moodle
  enabled: true
  master:
    persistence:
      accessModes:
      - ReadWriteOnce
      enabled: true
      size: 8Gi
  replication:
    enabled: false
metrics:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.7.0-debian-10-r39
  podAnnotations:
    prometheus.io/port: "9117"
    prometheus.io/scrape: "true"
moodleEmail: user@example.com
moodleSkipInstall: "no"
moodleUsername: user
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 8Gi
podAnnotations: {}
readinessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 30
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 3
resources:
  requests:
    cpu: 300m
    memory: 512Mi
service:
  externalTrafficPolicy: Cluster
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  port: 80
  type: LoadBalancer
