apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apaches.apache.netzlink.com
spec:
  group: apache.netzlink.com
  names:
    kind: Apache
    listKind: ApacheList
    plural: apaches
    singular: apache
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
