apiVersion: apache.netzlink.com/v1alpha1
kind: Apache
metadata:
  name: example-apache
spec:
  # Default values copied from <project_dir>/helm-charts/apache/values.yaml
  
  affinity: {}
  cloneHtdocsFromGit:
    branch: null
    enabled: false
    extraVolumeMounts: []
    interval: 60
    repository: null
    resources: {}
  commonAnnotations: {}
  commonLabels: {}
  extraDeploy: []
  extraEnvVars: []
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: null
  git:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/git
    tag: 2.32.0-debian-10-r26
  global:
    imagePullSecrets: []
    imageRegistry: null
  hostAliases:
  - hostnames:
    - status.localhost
    ip: 127.0.0.1
  htdocsConfigMap: null
  htdocsPVC: null
  httpdConfConfigMap: null
  image:
    debug: false
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/apache
    tag: 2.4.48-debian-10-r28
  ingress:
    annotations: {}
    apiVersion: null
    certManager: false
    enabled: false
    hostname: example.local
    hosts: []
    path: /
    pathType: ImplementationSpecific
    secrets: []
    tls:
    - hosts:
      - example.local
      secretName: example.local-tls
  initContainers: {}
  kubeVersion: null
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 180
    path: /
    periodSeconds: 20
    port: http
    successThreshold: 1
    timeoutSeconds: 5
  metrics:
    enabled: false
    image:
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: docker.io
      repository: bitnami/apache-exporter
      tag: 0.9.0-debian-10-r25
    podAnnotations:
      prometheus.io/port: "9117"
      prometheus.io/scrape: "true"
    resources:
      limits: {}
      requests: {}
  nameOverride: null
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  podAffinityPreset: ""
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    path: /
    periodSeconds: 10
    port: http
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources:
    limits: {}
    requests: {}
  service:
    annotations: {}
    externalTrafficPolicy: Cluster
    httpsPort: 443
    loadBalancerIP: null
    nodePorts:
      http: ""
      https: ""
    port: 80
    type: LoadBalancer
  sidecars: {}
  tolerations: []
  vhostsConfigMap: null
  
