apiVersion: apache.netzlink.com/v1alpha1
kind: Apache
metadata:
  name: example-apache
spec:
  # Default values copied from <project_dir>/helm-charts/apache/values.yaml
  
  affinity: {}
  cloneHtdocsFromGit:
    enabled: false
    extraVolumeMounts: []
    interval: 60
    resources: {}
  commonAnnotations: {}
  commonLabels: {}
  extraDeploy: []
  extraEnvVars: []
  extraVolumeMounts: []
  extraVolumes: []
  git:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/git
    tag: 2.31.1-debian-10-r22
  hostAliases:
  - hostnames:
    - status.localhost
    ip: 127.0.0.1
  image:
    debug: false
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/apache
    tag: 2.4.46-debian-10-r232
  ingress:
    annotations: {}
    apiVersion: null
    certManager: false
    enabled: false
    hostname: example.local
    path: /
    pathType: ImplementationSpecific
    secrets: null
    tls:
    - hosts:
      - example.local
      secretName: example.local-tls
  initContainers: {}
  kubeVersion: null
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 180
    path: /
    periodSeconds: 20
    port: http
    successThreshold: 1
    timeoutSeconds: 5
  metrics:
    enabled: false
    image:
      pullPolicy: IfNotPresent
      registry: docker.io
      repository: bitnami/apache-exporter
      tag: 0.8.0-debian-10-r357
    podAnnotations:
      prometheus.io/port: "9117"
      prometheus.io/scrape: "true"
    resources:
      limits: {}
      requests: {}
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  podAffinityPreset: ""
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    path: /
    periodSeconds: 10
    port: http
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources:
    limits: {}
    requests: {}
  service:
    annotations: {}
    externalTrafficPolicy: Cluster
    httpsPort: 443
    nodePorts:
      http: ""
      https: ""
    port: 80
    type: LoadBalancer
  sidecars: {}
  tolerations: []
  
