apiVersion: apache.netzlink.com/v1alpha1
kind: Apache
metadata:
  name: example-apache
spec:
  # Default values copied from <project_dir>/helm-charts/apache/values.yaml
  
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 11
    minReplicas: 1
    targetCPU: 50
    targetMemory: 50
  cloneHtdocsFromGit:
    branch: ""
    enableAutoRefresh: true
    enabled: false
    extraVolumeMounts: []
    interval: 60
    repository: ""
    resources: {}
  commonAnnotations: {}
  commonLabels: {}
  extraDeploy: []
  extraEnvVars: []
  extraPodSpec: {}
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: ""
  git:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/git
    tag: 2.34.1-debian-10-r23
  global:
    imagePullSecrets: []
    imageRegistry: ""
  hostAliases:
  - hostnames:
    - status.localhost
    ip: 127.0.0.1
  htdocsConfigMap: ""
  htdocsPVC: ""
  httpdConfConfigMap: ""
  image:
    debug: false
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/apache
    tag: 2.4.52-debian-10-r0
  ingress:
    annotations: {}
    apiVersion: ""
    enabled: false
    hostname: example.local
    hosts: []
    ingressClassName: ""
    path: /
    pathType: ImplementationSpecific
    secrets: []
    selfSigned: false
    tls:
    - hosts:
      - example.local
      secretName: example.local-tls
  initContainers: []
  kubeVersion: ""
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 180
    path: /
    periodSeconds: 20
    port: http
    successThreshold: 1
    timeoutSeconds: 5
  metrics:
    enabled: false
    image:
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: docker.io
      repository: bitnami/apache-exporter
      tag: 0.11.0-debian-10-r2
    podAnnotations:
      prometheus.io/port: "9117"
      prometheus.io/scrape: "true"
    resources:
      limits: {}
      requests: {}
  nameOverride: ""
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  pdb:
    create: false
    maxUnavailable: ""
    minAvailable: 1
  podAffinityPreset: ""
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    path: /
    periodSeconds: 10
    port: http
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources:
    limits: {}
    requests: {}
  service:
    annotations: {}
    externalTrafficPolicy: Cluster
    httpsPort: 443
    loadBalancerIP: ""
    nodePorts:
      http: ""
      https: ""
    port: 80
    type: LoadBalancer
  sidecars: []
  tolerations: []
  topologySpreadConstraints: []
  vhostsConfigMap: ""
  
