{{ if and (.Files.Glob "files/httpd.conf") (not .Values.httpdConfConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-httpd-conf
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
{{ (.Files.Glob "files/httpd.conf").AsConfig | indent 2 }}
{{ end }}
