{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apache.serviceAccountName" . }}
  labels:
{{ include "apache.labels" . | nindent 4 }}
{{- end -}}
