apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: moodles.moodle.netzlink.com
spec:
  group: moodle.netzlink.com
  names:
    kind: Moodle
    listKind: MoodleList
    plural: moodles
    singular: moodle
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
