name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
   - cron: '0 4 * * *' # Daily at 04:00
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build test operator
      uses: ./
      id: builder
    - name: Get the output time
      run: echo "The time was ${{ steps.builder.outputs.time }}"
